# Generated by Django 2.2.1 on 2019-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0005_catalog_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='catalogs', related_query_name='catalog', to='flashdeal.Image'),
        ),
    ]
