# Generated by Django 2.2.1 on 2019-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0006_auto_20190602_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='catalogs', related_query_name='catalog', to='flashdeal.Video'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Verified'), (1, 'Verified'), (2, 'Rejected'), (3, 'Disabled'), (3, 'Submitted for approval')], default=0),
        ),
    ]
