# Generated by Django 2.2.1 on 2019-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0009_auto_20190605_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashdeal',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
