# Generated by Django 2.2.1 on 2019-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0010_flashdeal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='flashdeal.ProductColor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='flashdeal.ProductSize'),
        ),
    ]
