# Generated by Django 2.2.1 on 2019-06-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0011_auto_20190606_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
