# Generated by Django 2.2.1 on 2019-06-14 14:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('flashdeal', '0016_order_payment_tracking'), ('flashdeal', '0017_basket'), ('flashdeal', '0018_auto_20190614_1334')]

    dependencies = [
        ('flashdeal', '0015_auto_20190611_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('tracking_type', models.CharField(max_length=500)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=500, unique=True)),
                ('gateway_order_id', models.CharField(max_length=500, unique=True)),
                ('gateway', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currency', models.CharField(max_length=500)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', related_query_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Just created'), (1, 'Paid'), (2, 'Vendor Received'), (3, 'Is Shipping'), (4, 'Delivered'), (5, 'Canceled')], default=0)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('pin_code', models.CharField(max_length=500)),
                ('alternate_contact', models.CharField(blank=True, max_length=500, null=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='flashdeal.Payment')),
                ('products', models.ManyToManyField(to='flashdeal.Product')),
                ('tracking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flashdeal.Tracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='flashdeal.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='basket', related_query_name='basket', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
