# Generated by Django 2.2.1 on 2019-06-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0016_order_payment_tracking_squashed_0018_auto_20190614_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
    ]
