# Generated by Django 2.2.1 on 2019-06-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('flashdeal', '0017_remove_payment_currency'), ('flashdeal', '0018_auto_20190616_0827'), ('flashdeal', '0019_auto_20190616_0827'), ('flashdeal', '0020_vendor_state'), ('flashdeal', '0021_auto_20190616_1643')]

    dependencies = [
        ('flashdeal', '0016_order_payment_tracking_squashed_0018_auto_20190614_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awb_number', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('actual_weight', models.PositiveIntegerField(default=0)),
                ('volumetric_weight', models.PositiveIntegerField(default=0)),
                ('pincode', models.PositiveIntegerField(default=0)),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_address_pincode', models.PositiveIntegerField(default=0)),
                ('rto_name', models.CharField(max_length=500)),
                ('rto_city', models.CharField(max_length=500)),
                ('rto_state', models.CharField(choices=[('andhra-pradesh-hyderabad', 'Andhra Pradesh – Hyderabad'), ('arunachal-pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal-pradesh', 'Himachal Pradesh'), ('jammu-and-kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya-pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil-nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar-pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west-bengal', 'West Bengal'), ('andaman-and-nicobar-islands', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra-and-nagar-haveli', 'Dadra and Nagar Haveli'), ('daman-and-diu', 'Daman and Diu'), ('lakshadweep', 'Lakshadweep'), ('delhi', 'Delhi'), ('puducherry', 'Puducherry')], max_length=500)),
                ('rto_contact_no', models.CharField(blank=True, max_length=500, null=True)),
                ('rto_address', models.CharField(blank=True, max_length=500, null=True)),
                ('rto_pincode', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upper_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashdeal.ProductColor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alternate_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[(0, 'home'), (1, 'office')], default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='alternate_customer_contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='c_city',
            field=models.CharField(default='city1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='c_state',
            field=models.CharField(choices=[('andhra-pradesh-hyderabad', 'Andhra Pradesh – Hyderabad'), ('arunachal-pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal-pradesh', 'Himachal Pradesh'), ('jammu-and-kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya-pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil-nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar-pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west-bengal', 'West Bengal'), ('andaman-and-nicobar-islands', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra-and-nagar-haveli', 'Dadra and Nagar Haveli'), ('daman-and-diu', 'Daman and Diu'), ('lakshadweep', 'Lakshadweep'), ('delhi', 'Delhi'), ('puducherry', 'Puducherry')], default='bihar', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='qweqw', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Just created'), (1, 'Paid and processing'), (2, 'Vendor Received'), (3, 'Is Shipping'), (4, 'Delivered'), (5, 'Canceled')], default=0),
        ),
        migrations.DeleteModel(
            name='ProductSizeStock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', related_query_name='variant', to='flashdeal.Product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashdeal.ProductSize'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flashdeal.DeliveryInfo'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', through='flashdeal.ProductVariant', to='flashdeal.ProductColor'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='flashdeal.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', through='flashdeal.ProductVariant', to='flashdeal.ProductSize'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(choices=[('andhra-pradesh-hyderabad', 'Andhra Pradesh – Hyderabad'), ('arunachal-pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal-pradesh', 'Himachal Pradesh'), ('jammu-and-kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya-pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil-nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar-pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west-bengal', 'West Bengal'), ('andaman-and-nicobar-islands', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra-and-nagar-haveli', 'Dadra and Nagar Haveli'), ('daman-and-diu', 'Daman and Diu'), ('lakshadweep', 'Lakshadweep'), ('delhi', 'Delhi'), ('puducherry', 'Puducherry')], default='assam', max_length=500),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='images',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='videos',
        ),
    ]
