# Generated by Django 2.2.1 on 2019-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0017_remove_payment_currency_squashed_0021_auto_20190616_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='basket',
            name='product_variant',
            field=models.ManyToManyField(to='flashdeal.ProductVariant'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_variant',
            field=models.ManyToManyField(to='flashdeal.ProductVariant'),
        ),
    ]
