# Generated by Django 2.2.1 on 2019-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0018_auto_20190616_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', through='flashdeal.ProductVariant', to='flashdeal.ProductColor'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='flashdeal.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', through='flashdeal.ProductVariant', to='flashdeal.ProductSize'),
        ),
    ]
