# Generated by Django 2.2.1 on 2019-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0020_auto_20190617_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_type',
            field=models.CharField(default='box', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='ind', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(default='124124', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='product', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_sale_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.CharField(default='item', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='volumetric_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
