# Generated by Django 2.2.1 on 2019-06-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0021_auto_20190617_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_sale_value',
        ),
    ]
