# Generated by Django 2.2.1 on 2019-06-17 17:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0022_remove_product_product_sale_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
