# Generated by Django 2.2.1 on 2019-06-17 18:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0027_auto_20190617_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awb_number', models.CharField(max_length=500)),
                ('actual_weight', models.PositiveIntegerField(default=0)),
                ('volumetric_weight', models.PositiveIntegerField(default=0)),
                ('pincode', models.PositiveIntegerField(default=0)),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_address_pincode', models.PositiveIntegerField(default=0)),
                ('rto_name', models.CharField(max_length=500)),
                ('rto_city', models.CharField(max_length=500)),
                ('rto_state', models.CharField(choices=[('andhra-pradesh-hyderabad', 'Andhra Pradesh – Hyderabad'), ('arunachal-pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal-pradesh', 'Himachal Pradesh'), ('jammu-and-kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya-pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil-nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar-pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west-bengal', 'West Bengal'), ('andaman-and-nicobar-islands', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra-and-nagar-haveli', 'Dadra and Nagar Haveli'), ('daman-and-diu', 'Daman and Diu'), ('lakshadweep', 'Lakshadweep'), ('delhi', 'Delhi'), ('puducherry', 'Puducherry')], max_length=500)),
                ('rto_contact_no', models.CharField(blank=True, max_length=500, null=True)),
                ('rto_address', models.CharField(blank=True, max_length=500, null=True)),
                ('rto_pincode', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(default=0)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flashdeal.DeliveryInfo'),
        ),
    ]
