# Generated by Django 2.2.1 on 2019-06-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0028_auto_20190617_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='awb_number',
            field=models.CharField(blank=True, help_text='Will get one form AWB number data if not specific', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'not_send'), (1, 'success'), (2, 'failed')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', related_query_name='order', to='flashdeal.DeliveryInfo'),
        ),
    ]
