# Generated by Django 2.2.1 on 2019-06-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0029_auto_20190618_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flashdeal.DeliveryInfo'),
        ),
    ]
