# Generated by Django 2.2.1 on 2019-06-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0030_auto_20190618_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_info',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_info', to='flashdeal.Order'),
            preserve_default=False,
        ),
    ]
