# Generated by Django 2.2.1 on 2019-06-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0031_auto_20190618_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_name', models.CharField(max_length=500)),
                ('warehouse_address', models.CharField(max_length=500)),
                ('destination_pincode', models.CharField(max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount (inclusive GST) of the AWB', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price (exclusive of GST) of the order', max_digits=10)),
                ('address_line', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('sms_contact', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='return_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='flashdeal.ReturnOrder'),
        ),
    ]
