# Generated by Django 2.2.1 on 2019-06-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0032_auto_20190621_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='images',
            field=models.ManyToManyField(related_name='vendors', related_query_name='vendor', to='flashdeal.Image'),
        ),
    ]
