# Generated by Django 2.2.2 on 2019-06-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0035_basket_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_variants',
            field=models.ManyToManyField(through='flashdeal.ProductVariantOrder', to='flashdeal.ProductVariant'),
        ),
    ]
