# Generated by Django 2.2.2 on 2019-06-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0037_returnorder_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_order',
        ),
        migrations.AddField(
            model_name='returnorder',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='return_order', to='flashdeal.Order'),
            preserve_default=False,
        ),
    ]
