# Generated by Django 2.2.2 on 2019-06-23 16:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeal', '0038_auto_20190623_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnorder',
            old_name='reason',
            new_name='name',
        ),
        migrations.AddField(
            model_name='returnorder',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'not_send'), (1, 'success'), (2, 'failed')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Just created'), (1, 'Paid and processing'), (2, 'Vendor Received'), (3, 'Is Shipping'), (4, 'Delivered'), (5, 'Canceled'), (6, 'Return')], default=0),
        ),
    ]
