
STATE_LIST = [
    ('andhra-pradesh-hyderabad', 'Andhra Pradesh – Hyderabad'),
    ('arunachal-pradesh', 'Arunachal Pradesh'),
    ('assam', 'Assam'),
    ('bihar', 'Bihar'),
    ('chhattisgarh', 'Chhattisgarh'),
    ('goa', 'Goa'),
    ('gujarat', 'Gujarat'),
    ('haryana', 'Haryana'),
    ('himachal-pradesh', 'Himachal Pradesh'),
    ('jammu-and-kashmir', 'Jammu and Kashmir'),
    ('jharkhand', 'Jharkhand'),
    ('karnataka', 'Karnataka'),
    ('kerala', 'Kerala'),
    ('madhya-pradesh', 'Madhya Pradesh'),
    ('maharashtra', 'Maharashtra'),
    ('manipur', 'Manipur'),
    ('meghalaya', 'Meghalaya'),
    ('mizoram', 'Mizoram'),
    ('nagaland', 'Nagaland'),
    ('odisha', 'Odisha'),
    ('punjab', 'Punjab'),
    ('rajasthan', 'Rajasthan'),
    ('sikkim', 'Sikkim'),
    ('tamil-nadu', 'Tamil Nadu'),
    ('telangana', 'Telangana'),
    ('tripura', 'Tripura'),
    ('uttar-pradesh', 'Uttar Pradesh'),
    ('uttarakhand', 'Uttarakhand'),
    ('west-bengal', 'West Bengal'),
    ('andaman-and-nicobar-islands', 'Andaman and Nicobar Islands'),
    ('chandigarh', 'Chandigarh'),
    ('dadra-and-nagar-haveli', 'Dadra and Nagar Haveli'),
    ('daman-and-diu', 'Daman and Diu'),
    ('lakshadweep', 'Lakshadweep'),
    ('delhi', 'Delhi'),
    ('puducherry', 'Puducherry')
]
